# Generated by Django 4.0 on 2022-04-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('sex', models.BooleanField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师信息表',
            },
        ),
    ]
